name: SpawnWithItems
main: LDX\SpawnWithItems\Main
version: 2.0
api: [1.1.0]
author: LDX
load: POSTWORLD
website: https://github.com/LDX-MCPE/SpawnWithItems
permissions:
  spawnwithitems:
    description: "Allows access to all SpawnWithItems features."
    default: op
    children:
      spawnwithitems.receive:
        description: "Allows access to receiving items when you spawn."
        default: true
